import { promises as fs } from 'fs';
import path from 'path';

// Generates src/themes/theme.ts from all @variant blocks inside src/themes/*.css
// Run with: `bunx tsx src/scripts/generate-themes.ts` or `npx tsx src/scripts/generate-themes.ts`

const THEMES_DIR = path.resolve(__dirname, '..', 'themes');
const OUTPUT_FILE = path.join(THEMES_DIR, 'theme.ts');

const VARIANT_REGEX = /@variant\s+([\w-]+)\s*\{([^}]*)\}/g;
const VAR_REGEX = /--([\w-]+)\s*:\s*([^;]+);/g;

export type ThemeVars = Record<string, string>;
export type ThemeMap = Record<string, ThemeVars>;

const toCamel = (input: string) => input.replace(/-([a-z0-9])/gi, (_, g1) => g1.toUpperCase());

async function getCssFiles(): Promise<string[]> {
  const entries = await fs.readdir(THEMES_DIR, { withFileTypes: true });
  return (
    entries
      .filter((ent) => ent.isFile() && ent.name.endsWith('.css'))
      .map((ent) => path.join(THEMES_DIR, ent.name))
      // keep stable order for deterministic output
      .sort()
  );
}

function parseVariants(css: string): ThemeMap {
  const themes: ThemeMap = {};
  let variantMatch: RegExpExecArray | null;

  while ((variantMatch = VARIANT_REGEX.exec(css)) !== null) {
    const [, variantName, body] = variantMatch;
    const vars: ThemeVars = {};
    let varMatch: RegExpExecArray | null;

    while ((varMatch = VAR_REGEX.exec(body)) !== null) {
      const [, key, value] = varMatch;
      vars[toCamel(key)] = value.trim();
    }

    themes[variantName] = vars;
  }

  return themes;
}

async function buildThemeMap(): Promise<ThemeMap> {
  const files = await getCssFiles();
  const all: ThemeMap = {};
  const allKeys = new Set<string>();

  for (const file of files) {
    const content = await fs.readFile(file, 'utf-8');
    const themes = parseVariants(content);
    for (const [name, vars] of Object.entries(themes)) {
      all[name] = vars;
      Object.keys(vars).forEach((k) => allKeys.add(k));
    }
  }

  // Ensure every theme has the same keys (Uniwind requirement)
  const requiredKeys = Array.from(allKeys);
  for (const [name, vars] of Object.entries(all)) {
    requiredKeys.forEach((key) => {
      if (!(key in vars)) {
        vars[key] = '';
      }
    });
  }

  return all;
}

async function writeThemeTs(themeMap: ThemeMap) {
  const data = JSON.stringify(themeMap, null, 2);
  const contents = `// This file is auto-generated by src/scripts/generate-themes.ts\n// Do not edit manually.\n\nexport const themes = ${data} as const;\n\nexport type ThemeName = keyof typeof themes;\nexport type ThemeVarKey = keyof (typeof themes)[ThemeName];\nexport type ThemeVars = Record<ThemeVarKey, string>;\nexport type ThemeMap = Record<ThemeName, ThemeVars>;\n\n`;

  await fs.writeFile(OUTPUT_FILE, contents, 'utf-8');
  console.log(`Generated ${OUTPUT_FILE}`);
}

async function main() {
  const themeMap = await buildThemeMap();
  await writeThemeTs(themeMap);
}

main().catch((err) => {
  console.error('Failed to generate themes:', err);
  process.exitCode = 1;
});
