import * as RNFS from '@dr.pogodin/react-native-fs';

export const EXTERNAL_LINKS = {
  GITHUB_REPOSITORY_API: 'https://api.github.com/repos/uwumilabs/uwumi',
  GITHUB_RELEASES_API: 'https://api.github.com/repos/uwumilabs/uwumi/releases',
  GITHUB_LATEST_RELEASE_API: 'https://api.github.com/repos/uwumilabs/uwumi/releases/latest',
  GITHUB_REPOSITORY: 'https://github.com/uwumilabs/uwumi',
  GITHUB_LATEST_RELEASE: 'https://github.com/uwumilabs/uwumi/releases/latest',
  DISCORD_SERVER: 'https://discord.gg/n7xVPxbG4R',
  PROJECT_WEBSITE: 'https://uwumi-dash.netlify.app/',
} as const;

export const SUB_LANGUAGE = {
  ALL: 'all',
  Abkhazian: 'abk',
  Afrikaans: 'afr',
  Albanian: 'alb',
  Amharic: 'amh',
  Arabic: 'ara',
  Aragonese: 'arg',
  Armenian: 'arm',
  Assamese: 'asm',
  Asturian: 'ast',
  Azerbaijani: 'aze',
  Basque: 'baq',
  Belarusian: 'bel',
  Bengali: 'ben',
  Bosnian: 'bos',
  Breton: 'bre',
  Bulgarian: 'bul',
  Burmese: 'bur',
  Catalan: 'cat',
  'Chinese (Cantonese)': 'zhc',
  'Chinese (simplified)': 'chi',
  'Chinese (traditional)': 'zht',
  'Chinese bilingual': 'zhe',
  Croatian: 'hrv',
  Czech: 'cze',
  Danish: 'dan',
  Dari: 'prs',
  Dutch: 'dut',
  English: 'eng',
  Esperanto: 'epo',
  Estonian: 'est',
  Extremaduran: 'ext',
  Finnish: 'fin',
  French: 'fre',
  Gaelic: 'gla',
  Galician: 'glg',
  Georgian: 'geo',
  German: 'ger',
  Greek: 'ell',
  Hebrew: 'heb',
  Hindi: 'hin',
  Hungarian: 'hun',
  Icelandic: 'ice',
  Igbo: 'ibo',
  Indonesian: 'ind',
  Interlingua: 'ina',
  Irish: 'gle',
  Italian: 'ita',
  Japanese: 'jpn',
  Kannada: 'kan',
  Kazakh: 'kaz',
  Khmer: 'khm',
  Korean: 'kor',
  Kurdish: 'kur',
  Kyrgyz: 'kir',
  Latvian: 'lav',
  Lithuanian: 'lit',
  Luxembourgish: 'ltz',
  Macedonian: 'mac',
  Malay: 'may',
  Malayalam: 'mal',
  Manipuri: 'mni',
  Marathi: 'mar',
  Mongolian: 'mon',
  Montenegrin: 'mne',
  Navajo: 'nav',
  Nepali: 'nep',
  'Northern Sami': 'sme',
  Norwegian: 'nor',
  Occitan: 'oci',
  Odia: 'ori',
  Persian: 'per',
  Polish: 'pol',
  Portuguese: 'por',
  'Portuguese (BR)': 'pob',
  'Portuguese (MZ)': 'pom',
  Pushto: 'pus',
  Romanian: 'rum',
  Russian: 'rus',
  Santali: 'sat',
  Serbian: 'scc',
  Sindhi: 'snd',
  Sinhalese: 'sin',
  Slovak: 'slo',
  Slovenian: 'slv',
  Somali: 'som',
  'Sorbian languages': 'wen',
  'South Azerbaijani': 'azb',
  Spanish: 'spa',
  'Spanish (EU)': 'spn',
  'Spanish (LA)': 'spl',
  Swahili: 'swa',
  Swedish: 'swe',
  Syriac: 'syr',
  Tagalog: 'tgl',
  Tamil: 'tam',
  Tatar: 'tat',
  Telugu: 'tel',
  Tetum: 'tet',
  Thai: 'tha',
  'Toki Pona': 'tok',
  Turkish: 'tur',
  Turkmen: 'tuk',
  Ukrainian: 'ukr',
  Urdu: 'urd',
  Uzbek: 'uzb',
  Vietnamese: 'vie',
  Welsh: 'wel',
} as const;

export const UWUMI_DIR = `${RNFS.ExternalStorageDirectoryPath}/uwumi`;
