// NOTE: This file is generated by uniwind and it should not be edited manually.
/// <reference types="uniwind/types" />

declare module 'uniwind' {
    export interface UniwindConfig {
        themes: readonly ['light', 'dark', 'default-light', 'default-dark', 'cloudflare-light', 'cloudflare-dark', 'cotton-candy-light', 'cotton-candy-dark']
    }
}

export {}
